### ISSUE TITLE
Docs are wrong

### ISSUE THREAD

**Issue by Murlocks** [rickstaa/Todoist_Global_Shortcuts_WIN10#6]
**Describe the bug**
Docs seem to be outdated. Binding to show todo-ist was moved to ctrl+alt+t.

**To Reproduce**
install via instructions
press ctrl+alt+s
nothing happens

**Expected behavior**
todo-ist shows

**Desktop (please complete the following information):**
 - TODOIST version: 2.1.6212.0 Desktop Production
 - Work arround type: AHK

**Comment by rickstaa** [comment]
@Murlocks Thank you so much for bringing this to my attention! I myself use the ctrl+s shortkey while the default global shortkey is ctrl+t. I updated the docs. Feel free to create any additional pull request if you see something else you would like to change.
