### ISSUE TITLE
How can I change the shortcuts?

### ISSUE THREAD

**Issue by ghost** [rickstaa/Todoist_Global_Shortcuts_WIN10#7]
An app I use already uses the configuration of one of the global shortcuts. I need the shortcuts of both apps, but I find it annoying that they're bound to the same configuration.

I'd like to change the shortcut configuration for Todoist's global shortcuts.

I've tried changing the shortcut of the other app, but it doesn't have an option for that.

By the way, I'm using the AHK workaround in my Win 8.1 PC.

**Comment by rickstaa** [comment]
@Rainbow-Moonshine That's an excellent question! I forgot to explain that in the documentation. So this issue will be a good reference. You can change the `open todoist` shortcuts by modifying [L40](https://github.com/rickstaa/todoist-global-shortcuts-WIN10/blob/b47003544dbfeed33e965b488b315314925cf818/TODOIST_AHK/Todoist_global_shortcuts.ahk#L40) of the [Todoist_global_shortcuts.ahk ](https://github.com/rickstaa/todoist-global-shortcuts-WIN10/blob/master/TODOIST_AHK/Todoist_global_shortcuts.ahk) file:

https://github.com/rickstaa/todoist-global-shortcuts-WIN10/blob/b47003544dbfeed33e965b488b315314925cf818/TODOIST_AHK/Todoist_global_shortcuts.ahk#L40

The `Open todoist and add task shortcut` shortcut can be changed by modifying [L70](https://github.com/rickstaa/todoist-global-shortcuts-WIN10/blob/b47003544dbfeed33e965b488b315314925cf818/TODOIST_AHK/Todoist_global_shortcuts.ahk#L70) of the [Todoist_global_shortcuts.ahk ](https://github.com/rickstaa/todoist-global-shortcuts-WIN10/blob/master/TODOIST_AHK/Todoist_global_shortcuts.ahk) file. 

https://github.com/rickstaa/todoist-global-shortcuts-WIN10/blob/b47003544dbfeed33e965b488b315314925cf818/TODOIST_AHK/Todoist_global_shortcuts.ahk#L70

You can find the exact syntax for changing these shortcuts in the [autohotkey documentation](https://www.autohotkey.com/). Hope that helps! Let me know if you have any other questions.

**Comment by ghost** [comment]
I've modified the lines to my desired shortcuts and they work perfectly. Thank you very much for your work and your comment!
